version: "3.7"

services:
  express-typescript-microservice:
    image: express-typescript-microservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-typescript-microservice
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
